name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

jobs:
  pr_review:
    runs-on: ubuntu-latest

    if: ${{ github.event.sender.type != 'Bot' }}

    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PR-agent
        uses: Codium-ai/pr-agent@main
        with:
          api_key: ${{ secrets.OPEN_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/pr-agent-config.yml
          github_action_config.auto_review: 'true' # enable\disable auto review
          github_action_config.auto_describe: 'true' # enable\disable auto describe
          github_action_config.auto_improve: 'true' # enable\disable auto improve
